/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okq_lib_serial_SerialPortJni */

#ifndef _Included_com_okq_lib_serial_SerialPortJni
#define _Included_com_okq_lib_serial_SerialPortJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    setSpeed
 * Signature: (Ljava/io/FileDescriptor;I)I
 */
JNIEXPORT jint JNICALL Java_com_okq_lib_serial_SerialPortJni_setSpeed
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    setParity
 * Signature: (Ljava/io/FileDescriptor;III)I
 */
JNIEXPORT jint JNICALL Java_com_okq_lib_serial_SerialPortJni_setParity
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    openDev
 * Signature: (Ljava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_okq_lib_serial_SerialPortJni_openDev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    open485Dev
 * Signature: (Ljava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_okq_lib_serial_SerialPortJni_open485Dev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    closeDev
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_okq_lib_serial_SerialPortJni_closeDev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    close485Dev
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_okq_lib_serial_SerialPortJni_close485Dev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    readBytes
 * Signature: (Ljava/io/FileDescriptor;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_okq_lib_serial_SerialPortJni_readBytes
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    writeBytes
 * Signature: (Ljava/io/FileDescriptor;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_okq_lib_serial_SerialPortJni_writeBytes
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     com_okq_lib_serial_SerialPortJni
 * Method:    set485mod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_okq_lib_serial_SerialPortJni_set485mod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
